### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by MathewCNichols** [Entware-ng/Entware-ng#340] opened 2016-07-19 18:57 UTC
All,

Just ran an "opkg update" and "opkg upgrade." On upgrade I made it through most packages, but after the PHP package upgraded, the upgrade failed with a segmentation fault. I can't run an update, list, or upgrade without a seg fault now. I can only run a version check.

Any advice? Perhaps this is related to free space? I suppose that would be the easiest fix!

Current setup:
ASUS RT-N66U TomatoUSB Shibby v1.28
OPKG v.0.1.8
250MB free space on SD Card

**Comment by zyxmon** [comment] 2016-07-20 04:52
This is Entware-ng bug introduced with the latest update. Sorry. Here is a technical explanation. 
The previous versions had libncurses packages. This package was removed from Entware (openwrt style - to save space) and it is now "provided" by libncuresesw - https://github.com/Entware-ng/Entware-ng/blob/master/package/libs/ncurses/Makefile#L43
This causes opkg binary to segfault. This may also cause packages that depend from libncureses (without w) to stop working. We are investigating the situation and we hope we will provide a quick fix to the repository.
The current solution is to remove all libncurses* and dependent packages and reinstall them mannually:

```
opkg remove with --force-removal-of-dependent-packages libncurses
opkg remove with --force-removal-of-dependent-packages libncursesw
```

**Comment by MathewCNichols** [comment] 2016-07-20 12:14
Thanks for the reply zyxmon! Thank you for all of your work too! It's so greatly appreciated!

If I can't run "opkg remove" without a segfault, is my only option to reinstall?

**Comment by zyxmon** [comment] 2016-07-20 12:30
The segfault arises near the end of installations/upgrade procedure. But the bad thing is -  /opt/lib/opkg/status file can get corrupted (truncated). You will receive an error message about missing EOL in this case. 

Just try to execute the two above commands and opkg update/upgrade once more. I would not recommend to reinstall because of possible future changes in the repo. Please wait for a couple of days.

**Comment by zyxmon** [comment] 2016-07-20 12:33
I am going to test updated packages on arm. mipsel is outside of my area of responsibility.

**Comment by MathewCNichols** [comment] 2016-07-20 12:51
It looks like a reinstall might be my only option. Thank you for all of your suggestions.

**Comment by MathewCNichols** [comment] 2016-07-20 12:53
Perhaps I can rm the status file and give it another go.

**Comment by ryzhovau** [comment] 2016-07-20 13:06
Looks like `opkg` bug with `PROVIDES:=libncurses` directive. 
When packages status file is corrupted it's better to re-install Entware from scratch.

**Comment by zyxmon** [comment] 2016-07-20 14:09
@MathewCNichols it is better to copy status file to the safe place before any experiments.

**Comment by zyxmon** [comment] 2016-07-20 19:10
The issue is fixed in https://github.com/Entware-ng/Entware-ng/commit/641368528aaca9e0a2fcb3224f6474e35fc66cd0

@MathewCNichols - you can try to update/upgrade once more or reinstall from scratch after the new binaries arrive.

**Closed by zyxmon** 2016-07-20 19:10 UTC

**Comment by MathewCNichols** [comment] 2016-07-21 13:23
@zyxmon is there any way to reinstall or overwrite the status file without having to lose all of my customizations? I have a ton of packages installed and config files modified, daemons running, and more. I don't want to lose everything. :/

I can't run the --force-removal commands above without a segfault. I tried a manual "opkg install" with the new 1b nscurses and get segfaults too. I think I am SOL?

**Comment by zyxmon** [comment] 2016-07-21 14:30
If you have a corrupted status file - you'll have different errors.
Just try to run opkg update/upgrade once more. The repo was updated today.
If you will have some errors during update/upgrade - post your log on http://pastebin.com/

**Comment by MathewCNichols** [comment] 2016-07-21 14:50
Where can I get these logs? I can't install logread since my package manager is borked. :/

**Comment by zyxmon** [comment] 2016-07-21 14:54
From the console. 
You can also redirect stdout& stderr from opkg to a file.

**Comment by MathewCNichols** [comment] 2016-07-21 16:29
It looks like it is libxml causing the seg fault?

opkg update pastebin: http://pastebin.com/3pCpkHcy

**Comment by zyxmon** [comment] 2016-07-21 19:05
You do not need to add debug options without request.
There is nothing wrong with libxml2 and i cannot reproduce it on my mipsel and arm routers.
It can be caused by some file corruption when opkg crashed before.
But let us try some commands:
`opkg remove libxml2 --force-depends` 
'opkg install libxml2` 
`opkg upgrade` 

Please do not run the command if the previous one failed. Just post the log.

**Comment by MathewCNichols** [comment] 2016-07-21 19:25
I have to set the verbose to debug level, (-V4) otherwise stdout (&>) only shows "segmentation fault" in the log file.

I can't run any commands: info, list, remove, update, upgrade, install, etc. I think my setup is cooked.

**Comment by zyxmon** [comment] 2016-07-21 19:34
The only thing I can commend now is to save /opt/etc folder that usually holds configs to the safe place. You can also save status file and /opt/lib/opkg/info directory listing. This will help you to know the list of installed packages.

**Comment by zyxmon** [comment] 2016-07-21 19:37
All you can do now - is to reinstall and restore configs. Sorry - everyone makes mistakes.

**Comment by MathewCNichols** [comment] 2016-07-21 19:37
Alrighty, thank you for the tips and your time. It is greatly appreciated. I know this is only a hobby. It is mine too, although I'm not as savvy as you! :D

I will definitely reinstall. I love entware!
