### ISSUE TITLE
run entware-setup.sh get error

### ISSUE THREAD

**Issue by bigcat133** [Entware-ng/Entware-ng#798] opened 2017-11-04 16:49 UTC
### Package: <name>

For existing package:

update new firmware about meilin asusuwrt 382 beta3

For new package to be added:

i get error inf at run entware-setup.sh, error info as under:
`
--2017-11-04 16:38:10--  http://pkg.entware.net/binaries/armv7/installer/libc-2.23.so
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1227404 (1.2M) [application/octet-stream]
Saving to: '/opt/lib/libc-2.23.so'

/opt/lib/libc-2.23.so              100%[=============================================================>]   1.17M   279KB/s    in 4.4s    

2017-11-04 16:38:15 (270 KB/s) - '/opt/lib/libc-2.23.so' saved [1227404/1227404]

/opt/lib/libgcc_s.so.1: No such file or directory
Info: Basic packages installation...
Collected errors:
 * opkg_conf_load: Couldn't stat /opt/etc/opkg.conf: No such file or directory.
Collected errors:
 * opkg_conf_load: Couldn't stat /opt/etc/opkg.conf: No such file or directory.
/opt/usr/lib/locale/locale-archive: No such file or directory
Info: Congratulations!
Info: If there are no errors above then Entware-ng was successfully initialized.
Info: Add /opt/bin & /opt/sbin to your PATH variable
Info: Add '/opt/etc/init.d/rc.unslung start' to startup script for Entware-ng services to start
Info: Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues
`

### Platform:
my router is asus ac-86u , the run script entware-setup.sh is in the meilin asusuwrt 382 beta3 version

**Comment by zyxmon** [comment] 2017-11-04 19:15
Please contact Merlin here - https://www.snbforums.com/threads/beta-asuswrt-merlin-382-1-beta-is-available.41661/
Here you can find more info on entware+382 platform - https://github.com/Entware-ng/Entware-ng/issues/772

**Comment by ryzhovau** [comment] 2017-11-06 13:54
Duplicate of https://github.com/RMerl/asuswrt-merlin/issues/1519

**Closed by ryzhovau** 2017-11-06 13:54 UTC
