### ISSUE TITLE
Package Request:  nodogsplash

### ISSUE THREAD

**Issue by pdragon79** [Entware-ng/Entware-ng#296] opened 2016-05-27 21:33 UTC
Use case:  creating free WiFi hotspot for local low-income housing neighborhood kids.

Just wanted a free simple splash page to detail what the free hotspot is meant for.  (No illegal activities,  acceptable usages, etc...)

came across this:
https://github.com/Entware-ng/entware-routing/tree/master/nodogsplash

but I do not know how to compile.

Wanted to be able to use on a Asus Router RT-AC68u with Entware-ng installed.  (Arm7)

**Comment by pdragon79** [comment] 2016-05-27 21:42
On the Asus Router RT-AC68u, 

after I installed Entware-ng, I did a "opkg install nodogsplash"
came back with:
unknown package 'nodogsplash'

when I use "opkg update"
this is the repository:  http://pkg.entware.net/binaries/armv7/packages.gz

**Comment by ryzhovau** [comment] 2016-05-28 04:24
Duplicate of #295.

**Closed by ryzhovau** 2016-05-28 04:24 UTC

**Comment by pdragon79** [comment] 2016-05-28 05:31
That was a different request.. 295 wanted to use chili spot for commercial(?) purposes, but nodogsplash does not contain any ability (that I know of) for commercial use other then a splash page.

Thanks for entware, and thanks for reading the request at least. I guess I will have to find another solution.
