### ISSUE TITLE
Package request: mmv

### ISSUE THREAD

**Issue by rico666** [Entware-ng/Entware-ng#746] opened 2017-08-20 09:39 UTC
### Package: mmv

see e.g. https://aur.archlinux.org/packages/mmv/

killer features: Mass renaming of files possible on command line! Not sure how a NAS can live without it. :-)

I am using the x86_64 platform.

**Comment by ryzhovau** [comment] 2017-08-20 12:20
Duplicate of #624.

**Closed by ryzhovau** 2017-08-20 12:20 UTC
