### ISSUE TITLE
Top level make  fails on "C++ style comments are not allowed in ISO C90" 

### ISSUE THREAD

**Issue by faircreek** [Entware-ng/Entware-ng#705] opened 2017-07-08 09:36 UTC
I'm not writing this issue for the fun of it. I'm running Ubuntu 17.04 and If you follow https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources, you will get several failures on "C++ style comments are not allowed in ISO C90", and when you tmp fix it then you will get the same error a bit later, is there a way to turn off ISO C90 compiler setting on a global level or per package level?

Cheers Olof

PS: I'm using the armv7.config

PS: package/Makefile:105: recipe for target '/home/jorm/Qnap/Entware/Entware-ng/staging_dir/target-arm_cortex-a9_glibc-2.23_eabi/stamp/.package_compile' failed
make[1]: *** [/home/jorm/Qnap/Entware/Entware-ng/staging_dir/target-arm_cortex-a9_glibc-2.23_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jorm/Qnap/Entware/Entware-ng'
/home/jorm/Qnap/Entware/Entware-ng/include/toplevel.mk:206: recipe for target 'world' failed
make: *** [world] Error 2

World is a target, though the command that fails is the normal "make" as in 

**Rebuild repo**
make  

from the wiki

**Comment by ryzhovau** [comment] 2017-07-08 16:38
Duplicate of #704

**Closed by ryzhovau** 2017-07-08 16:38 UTC
