### ISSUE TITLE
OpenPrinting CUPS Filters NEW Package

### ISSUE THREAD

**Issue by davigre** [Entware-ng/Entware-ng#94] opened 2016-01-15 17:52 UTC
I'm not a programming expert but trying to add [CUPS Filters package](http://www.openprinting.org/download/cups-filters/), get this error when compiling one of the dependant packages ('poppler' already existing).
```
david@debian64:~/Entware-ng$ make -j1 V=s package/poppler/compile
make[1]: Entering directory '/home/david/Entware-ng'
make[2]: Entering directory '/home/david/Entware-ng/package/libs/toolchain'
make[2]: Leaving directory '/home/david/Entware-ng/package/libs/toolchain'
make[2]: Entering directory '/home/david/Entware-ng/package/libs/zlib'
make[2]: Leaving directory '/home/david/Entware-ng/package/libs/zlib'
make[2]: Entering directory '/home/david/Entware-ng/package/utils/bzip2'
make[2]: Leaving directory '/home/david/Entware-ng/package/utils/bzip2'
make[2]: Entering directory '/home/david/Entware-ng/feeds/packages/libs/freetype'
make[2]: Leaving directory '/home/david/Entware-ng/feeds/packages/libs/freetype'
make[2]: Entering directory '/home/david/Entware-ng/package/libs/libtool'
make[2]: Leaving directory '/home/david/Entware-ng/package/libs/libtool'
make[2]: Entering directory '/home/david/Entware-ng/feeds/packages/libs/libjpeg'
make[2]: Leaving directory '/home/david/Entware-ng/feeds/packages/libs/libjpeg'
make[2]: Entering directory '/home/david/Entware-ng/feeds/packages/libs/libpng'
make[2]: Leaving directory '/home/david/Entware-ng/feeds/packages/libs/libpng'
make[2]: Entering directory '/home/david/Entware-ng/feeds/packages/libs/tiff'
make[2]: Leaving directory '/home/david/Entware-ng/feeds/packages/libs/tiff'
make[2]: Entering directory '/home/david/Entware-ng/feeds/printing/libs/lcms2'
mkdir -p /home/david/Entware-ng/bin/mipselsf-uClibc/packages /home/david/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.9/lcms2-2.5/ipkg-mipselsf/lcms2/CONTROL /home/david/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.9/pkginfo
install -d -m0755 /home/david/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.9/lcms2-2.5/ipkg-mipselsf/lcms2/usr/bin /home/david/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.9/lcms2-2.5/ipkg-mipselsf/lcms2/usr/lib
install -m0755 /home/david/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.9/lcms2-2.5/ipkg-install/usr/bin/* /home/david/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.9/lcms2-2.5/ipkg-mipselsf/lcms2/usr/bin/
install: cannot stat '/home/david/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.9/lcms2-2.5/ipkg-install/usr/bin/*': No such file or directory
Makefile:47: recipe for target '/home/david/Entware-ng/bin/mipselsf-uClibc/packages/lcms2_2.5-1_mipselsf.ipk' failed
make[2]: *** [/home/david/Entware-ng/bin/mipselsf-uClibc/packages/lcms2_2.5-1_mipselsf.ipk] Error 1
make[2]: Leaving directory '/home/david/Entware-ng/feeds/printing/libs/lcms2'
package/Makefile:191: recipe for target 'package/feeds/printing/lcms2/compile' failed
make[1]: *** [package/feeds/printing/lcms2/compile] Error 2
make[1]: Leaving directory '/home/david/Entware-ng'
/home/david/Entware-ng/include/toplevel.mk:184: recipe for target 'package/poppler/compile' failed
make: *** [package/poppler/compile] Error 2
```

How can I resolve this?

Thank's.

**Comment by ryzhovau** [comment] 2016-01-16 04:47
Duplicate of https://github.com/Entware-ng/Entware-ng/issues/81

**Closed by ryzhovau** 2016-01-16 04:47 UTC
Labels: duplicate
