### ISSUE TITLE
openssh-sftp-client does not use dropbear ssh (hard-coded ssh path in sftp binary)

### ISSUE THREAD

**Issue by HunterZ** [Entware-ng/Entware-ng#197] opened 2016-03-12 16:59 UTC
Running sftp from openssh-sftp-client on Toastman MIPS TomatoUSB results in the following error:
```
exec: /opt/bin/ssh: No such file or directory
```
Toastman MIPS TomatoUSB provides dropbear ssh client v2012.55 in my path at `/usr/bin/ssh`, but Entware-ng openssh-sftp-client's sftp binary doesn't use it because of a hard-coded `/opt/bin/ssh` path as seen below:
```
# strings /opt/bin/sftp | grep ssh | grep /
/opt/bin/ssh
/tmp/ssh-XXXXXXXXXXXX
%s/ssh-XXXXXXXXXXXX
```
Workaround is to install openssh-client, but this is not listed as a package dependency for some reason.

**Comment by ryzhovau** [comment] 2016-03-13 05:09
Duplicate of https://github.com/Entware-ng/Entware-ng/issues/196

**Closed by ryzhovau** 2016-03-13 05:09 UTC

**Comment by HunterZ** [comment] 2016-03-13 05:16
Guess I won't report bugs here any more, as they get closed out of hand :(

**Comment by ryzhovau** [comment] 2016-03-13 06:43
1) Please, find out how SFTP is working and why it searches for SSH.
2) `openssh-sftp-client` was checked by other users and proven as working.
3) No need to add the same issue if previous was closed.
