### ISSUE TITLE
Package Request: pdnsd

### ISSUE THREAD

**Issue by plutoid** [Entware-ng/Entware-ng#513] opened 2017-01-15 05:12 UTC
hi,

It's very appreciating for adding pdnsd for mips arch!

also I have found as below, the first repo url seems doesn't work any more, it's pity, the other one is its homepage, hope this will help. :)
https://gitorious.org/pdnsd/pdnsd
http://members.home.nl/p.a.rombouts/pdnsd/dl.html

Regards,
Hua

**Comment by plutoid** [comment] 2017-01-15 05:38
also I have found as below, the first repo url seems doesn't work any more, it's pity, the other one is its homepage, hope this will help. :)
https://gitorious.org/pdnsd/pdnsd
http://members.home.nl/p.a.rombouts/pdnsd/dl.html

**Comment by ryzhovau** [comment] 2017-01-15 06:18
Duplicate of #408.

**Closed by ryzhovau** 2017-01-15 06:18 UTC
