### ISSUE TITLE
Package Request: Java (OpenJDK)

### ISSUE THREAD

**Issue by dafart** [Entware-ng/Entware-ng#617] opened 2017-04-08 08:02 UTC
I'd love to have minimserver running on my netgear r7000 with advanced tomato firmware running entware.

There appear to be a package for optware-ng (https://github.com/Optware/Optware-ng/tree/master/sources/openjdk8 )

But I don't think I have the skill to port this to entware.. I tried installing build environment for entware and use jre / jdk from the oracle site but that didn't work (java not found error).

Thanks in advance

**Comment by ryzhovau** [comment] 2017-04-08 08:15
Duplicate of #473.

**Closed by ryzhovau** 2017-04-08 08:15 UTC
