### ISSUE TITLE
Package Request: coova-chilli

### ISSUE THREAD

**Issue by alshstf** [Entware-ng/Entware-ng#468] opened 2016-12-10 17:31 UTC
Hello! I'd ask you to add [https://github.com/coova/coova-chilli](url)
It's software access controller for captive portal hotspots, in times more advanced then built-in Tomato one.
It's avalible as a package for OpenWRT, so it will be great if it will be avalible via Entware-ng too.

**Comment by ryzhovau** [comment] 2016-12-10 18:27
Duplicate of #295

**Closed by ryzhovau** 2016-12-10 18:27 UTC
