### ISSUE TITLE
possible binutils/libc issue

### ISSUE THREAD

**Issue by snova59** [Entware-ng/Entware-ng#365] opened 2016-08-20 22:14 UTC
I just upgraded my QNAP to gcc5.4.0 and now it's having issues compiling.

```
/opt/bin/ld: /share/CACHEDEV1_DATA/.qpkg/Entware-ng/bin/../lib/gcc/x86_64-openwrt-linux-gnu/5.4.0/crti.o: unrecognized relocation (0x2a) in section `.init'
/opt/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

I did just a little bit of looking, and found that it might be related to a libc bug

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808205

**Comment by zyxmon** [comment] 2016-08-21 05:24
Thanks for reporting. The issue is fixed by upgrading binutils package to 2.26.1.
I have checked that the issue is solved on Entware-3x fork, but there shouldn't be any difference.

**Closed by zyxmon** 2016-08-21 05:24 UTC
