### ISSUE TITLE
Package request "bareos"

### ISSUE THREAD

**Issue by mdallastella** [Entware-ng/Entware-ng#185] opened 2016-02-29 08:28 UTC
Hi,

it would be nice to have the [bareos](http://bareos.org) suite among with bacula (bareos is a fork of it).
Unfortunately recent bacula client has some issues to communicate with bareos director, so it would be great to have its native client.

If you need further information, I'm at your disposal.

Thank you.

**Comment by ryzhovau** [comment] 2016-02-29 08:28
Duplicate of https://github.com/Entware-ng/Entware-ng/issues/172

**Closed by ryzhovau** 2016-02-29 08:28 UTC

**Comment by vandendal** [comment] 2016-03-02 21:07
That's nice. Another vote for bareos :)
ryzhovau: What's the point against another backup solution in the repo?
