### ISSUE TITLE
Package request: sshpass

### ISSUE THREAD

**Issue by manoloonline** [Entware-ng/Entware-ng#612] opened 2017-04-02 20:21 UTC
### Package: sshpass

It would be very usefull to automatize tasks easily with cron for example with scp or rsync. Now to do that it is needed a complex config with a public key infrastructure

### Platform: Synology DSM 6.1 - arm7

**Comment by ryzhovau** [comment] 2017-04-03 06:46
Duplicate of #26

**Closed by ryzhovau** 2017-04-03 06:46 UTC
