### ISSUE TITLE
Postfix searches config outside of /opt

### ISSUE THREAD

**Issue by awhittall** [Entware-ng/Entware-ng#321] opened 2016-06-22 20:34 UTC
Running 'S69postfix start' generates:
`postfix: fatal: chdir(/usr/libexec/postfix): No such file or directory`

Running 'strings postfix | grep libexec' results in:
`/usr/libexec/postfix`

**Comment by ryzhovau** [comment] 2016-06-23 05:33
Duplicate of https://github.com/Entware-ng/Entware-ng/issues/2

**Closed by ryzhovau** 2016-06-23 05:33 UTC

**Comment by awhittall** [comment] 2016-06-23 05:59
Thanks Alexander - wasn't sure whether to report this error as new, or add it to your open issue (#2).
After fixing this (and similar errors) by adding entries to main.cf, I have an additional error reported. I am not sure how to describe this, but it appears to be a hard-coded suer 'root' ...
`[/opt/sbin] # /opt/sbin/postfix -c /opt/etc/postfix set-permissions`
`chown: unknown user name: root`

**Comment by zyxmon** [comment] 2016-06-23 09:16
May be aliases file can help to solve the issue?
Many embeded systems have admin user with uid=0. This case should be decribed somewhere.

**Comment by ryzhovau** [comment] 2016-06-23 09:49
This is an oldest issues here. I'm not using `postfix` and I see no easy solution to fix it. 
So I just sit on this and wait for some advanced user, who's qualified enough to make a patch/PR/etc.
