### ISSUE TITLE
dnsmasq does not work after upgrade

### ISSUE THREAD

**Issue by mackowiakp** [Entware-ng/Entware-ng#846] opened 2018-01-15 07:45 UTC
### Package: dnsmasq

I just upgraded Entware-ng to newest version but there is a problem with dnsmasq. It can not start at all. Below rapport error:

```
dnsmasq: unsupported option (check that dnsmasq was compiled with DHCP/TFTP/DNSSEC/DBus support) at line 9 of /opt/etc/dnsmasq.conf
# dnsmasq -v
Dnsmasq version 2.78  Copyright (c) 2000-2017 Simon Kelley
Compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN no-DHCP no-Lua TFTP conntrack ipset auth no-DNSSEC no-ID loop-detect inotify
```

How can I make dnsmasq running? Or downgrade to previous version?

My platform QNAP TS-453-A

**Comment by zyxmon** [comment] 2018-01-15 08:04
Duplicate of https://github.com/Entware-ng/Entware-ng/issues/845

**Closed by zyxmon** 2018-01-15 08:04 UTC
