### ISSUE TITLE
mlocate is missing 'mlocate' group entry:   groupadd mlocate needed

### ISSUE THREAD

**Issue by herrold** [Entware-ng/Entware-ng#843] opened 2018-01-10 23:34 UTC
### Package: mlocate

[/var/mlocate] # opkg install mlocate 
Installing mlocate (0.26-1) to root...
Downloading http://pkg.entware.net/binaries/armv5/mlocate_0.26-1_armv5soft.ipk
Configuring mlocate.
[/var/mlocate] # cd
[~] # updatedb
date
updatedb: can not find group `mlocate'
[~] # date

[~] # ls -al /etc/group /etc/passwd 
lrwxrwxrwx    1 admin    administ        12 Dec 12 21:07 /etc/group -> config/group
lrwxrwxrwx    1 admin    administ        13 Dec 12 21:07 /etc/passwd -> config/passwd
[~] # 

[~] # grep locate /etc/group
[~] # grep locate /etc/passwd
[~] #

**Comment by zyxmon** [comment] 2018-01-11 05:50
Duplicate of  https://github.com/Entware-ng/Entware-ng/issues/360
Entware is not responsible for users and groups on your device.
Use Entware-3x alternative installation, if your firmware supports 3x, to have more control on users and groups - https://github.com/Entware-for-kernel-3x

**Closed by zyxmon** 2018-01-11 05:50 UTC

**Comment by herrold** [comment] 2018-01-11 15:00
Reading at that link, I think I am able to cut to it, but the README.md lacks the PWD to CD to, to do the conversion

[/opt] # find /opt -name "feeds"
[/opt] # uname -a
Linux nas1-first 3.4.6 #1 Wed Dec 13 09:02:49 CST 2017 armv5tel unknown
[/opt] # time nice find / -name "feeds" | grep scripts
-sh: nice: command not found

real    0m0.864s
user    0m0.000s
sys     0m0.000s
[/opt] # opkg install nice
Unknown package 'nice'.
Collected errors:
 * opkg_install_cmd: Cannot install package nice.
[/opt] # opkg install coreutils
Package coreutils (8.23-3) installed in root is up to date.
[/opt] # opkg update
Downloading http://pkg.entware.net/binaries/armv5/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/packages
[/opt] #

**Comment by zyxmon** [comment] 2018-01-11 15:04
`opkg install coreutils-nice`
