### ISSUE TITLE
Avahi daemon startup error - 'nogroup' missing

### ISSUE THREAD

**Issue by PiotrC1** [Entware-ng/Entware-ng#376] opened 2016-08-26 06:33 UTC
Starting avahi-daemon via /opt/etc/init.d/S42avahi-daemon start causes error "Failed to find group 'nogroup'"

**Comment by ryzhovau** [comment] 2016-08-26 07:26
Duplicate of https://github.com/Entware-ng/Entware-ng/issues/377

**Closed by ryzhovau** 2016-08-26 07:26 UTC

**Comment by TCB13** [comment] 2017-09-23 15:39
Seems like this was never fixed and I can't start avahi... any tips? Is there another way to make it start?

**Comment by PiotrC1** [comment] 2017-09-23 16:12
Honestly? I'm not using entware-ng any more. Instead I reverted to optware-ng with perfect support.

**Comment by TCB13** [comment] 2017-09-23 17:08
Yeah still here. 😞

**Comment by zyxmon** [comment] 2017-09-23 19:46
Running avahi may depend on your device and firmware. For Asuswrt here is the solution
https://www.snbforums.com/threads/avahi-install.10218/

**Comment by TCB13** [comment] 2017-09-24 10:47
Running on R7000 but I'll give it a try later. Thanks!
