### ISSUE TITLE
Update Snort to maintained version

### ISSUE THREAD

**Issue by edbir1** [Entware-ng/Entware-ng#756] opened 2017-08-28 20:01 UTC
### Package: Snort

Could the Snort package for ARM7 be updated to the current (3.x+) version?  2.x is no longer supported.
Barnyard as support for Snort would be nice.

Thank you!

**Comment by ryzhovau** [comment] 2017-08-29 05:49
Duplicate of #695.

**Closed by ryzhovau** 2017-08-29 05:49 UTC
